### ISSUE TITLE
Sample data for email_layout and email_template tables

### ISSUE THREAD

**Issue by cyberfly** [jdtsoftware/laravel-email-templates#11]
Hi any sample data that I can refer to and test? What kind of data needed for email_layout table?

I simply filled with random data but unfortunately no email was send out (on Laravel 5.5, check using mailtrap)

Thanks

**Comment by thehelvetian** [comment]
`layout` simply holds the email's HTML layout. You need to add `{{content}}` somewhere in your layout so it gets replaced with your actual email `content`.

Layout:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mail Layout</title>
</head>
<body>
    {{content}}
</body>
</html>
```

Template:
```html
<p>Hello John Doe</p>
```

Result:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mail Layout</title>
</head>
<body>
    <p>Hello John Doe</p>
</body>
</html>
```

**Comment by cyberfly** [comment]
Thanks for your reply, will try again :)
