### ISSUE TITLE
Email layout and template examples

### ISSUE THREAD

**Issue by webexpert4rv** [jdtsoftware/laravel-email-templates#6]
Hello, 

Can you give any example of email layout and email template database content, also could not receive the email.

Thanks

**Comment by jbraud** [comment]
You can have anything you like in the email_layout table, as long as a {{content}} placeholder exists inside the layout, this is where the email_template entry is replaced.

The same goes for email_templates, consider; 
`
$mail = \EmailTemplate::fetch('registration', ['name' => 'Jon']);
`

In this case, you're able to use {{name}} anywhere in your email_template record (subject/body).
