### ISSUE TITLE
Sending Mail

### ISSUE THREAD

**Issue by webexpert4rv** [jdtsoftware/laravel-email-templates#7]
Hello,

This line is not sending mail, do we need to change something other then actual email id.
\Mail::to('foo@bar.com', $mail);

Actual mail sending syntex is 
  Mail::to($request->user())->send(new OrderShipped($order));

Are we misisng something ?

Thanks

**Comment by jbraud** [comment]
Hi, sorry about the delay I didn't see the alert about the issue.  The documentation needs updating as I'm changing quite a lot in there (though keeping the interface the same).

I'm not sure if you've given up on it in the last 8 days, but you're correct, that wouldn't send, it would be:

$mail = \EmailTemplate::fetch('registration', ['name' => 'Jon']);
\Mail::to('foo@bar.com')->send($mail);
