### ISSUE TITLE
how to change email from and email reply to?

### ISSUE THREAD

**Issue by jefsteward** [jdtsoftware/laravel-email-templates#9]
as title, how to change email from and email reply to?

**Comment by jbraud** [comment]
Hi jefsteward,
    Sorry I've been unavailable to reply.  I'm not quite sure I understand your question?  If you're referring to setting those fields on the sent email then you would do so normally through the Mail class: https://laravel.com/docs/5.4/mail

Unless of course I'm misunderstanding your issue, in which case can you please clarify.  Thanks.

**Comment by ezra-obiwale** [comment]
@jefsteward I think it's safe to close this issue.
